[global/wm]
margin-bottom = 0
margin-top = 0

[color]
background = #881d1f21
foreground = #eceff4

i3focused-background = #cc00acc1
i3focused-foreground = #1d1f21
i3focused-underline = #00000000

i3mode-background = #dde53935
i3mode-foreground = #eceff4

i3alert-background = #dde53935
i3alert-foreground = #eceff4

level0 = #eceff4
level1 = #eceff4
level2 = #eceff4
level3 = #eceff4
level4 = #eceff4


[bar/top]

width = 100%
height = 27
radius = 0
fixed-center = true

background = ${color.background}
foreground = ${color.foreground}

border-top-size = 0
border-right-size = 0
border-left-size = 0
border-color = #00000000

#fixed-center = true

padding-left = 0
padding-right = 0

module-margin-left = 1
module-margin-right = 2

#font-0 = monospace:size=10;2
font-0 = Cantarell:size=10.5;2
#font-0 = Liberation Sans:style=Medium:size=10;2
font-1 = Font Awesome 6 Brands,Font Awesome 6 Brands Regular:style=Regular:pixelsize=10;1
font-2 = Font Awesome 6 Free,Font Awesome 6 Free Solid:style=Solid:pixelsize=10;1
font-3 = Font Awesome v4 Compatibility,Font Awesome v4 Compatibility Regular:style=Regular:pixelsize=10;1
font-4 = Font Awesome 6 Free,Font Awesome 6 Free Regular:style=Regular:pixelsize=10;1

modules-left = powermenu 
modules-center = date

separator =

dim-value = 1.0

tray-position = right
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 2
tray-scale = 1.0
enable-ipc = true

[bar/bottom]

width = 100%
height = 27

radius = 0
fixed-center = true

background = ${color.background}
foreground = ${color.foreground}

border-right-size = 0
border-left-size = 0
border-color = #00000000

bottom = true

padding-left = 0
padding-right = 2

module-margin-left = 1
module-margin-right = 2

#font-0 = monospace:size=10;2
#font-0 = Liberation Sans:style=Regular:size=10;2
font-0 = Cantarell:size=10.5;2
font-1 = Font Awesome 6 Brands,Font Awesome 6 Brands Regular:style=Regular:pixelsize=10;1
font-2 = Font Awesome 6 Free,Font Awesome 6 Free Solid:style=Solid:pixelsize=10;1
font-3 = Font Awesome v4 Compatibility,Font Awesome v4 Compatibility Regular:style=Regular:pixelsize=10;1
font-4 = Font Awesome 6 Free,Font Awesome 6 Free Regular:style=Regular:pixelsize=10;1

modules-center = i3 
modules-right = cpu memory filesystem battery backlight-acpi
separator =
dim-value = 1.0

enable-ipc = true

[module/powermenu]
type = custom/text

content = 
content-background = ${color.i3focused-background}
content-foreground = ${color.foreground}
content-padding = 2

click-left = powermenu_t2
click-right = 

[module/date]
type = internal/date
interval = 60

date = " %d %a %b, %Y"

time = %I:%M %p

#format-prefix = 
#format-prefix-foreground = ${color.foreground}

label = %date% %time%


[module/cpu]
type = internal/cpu
interval = 5

#hgop double click
format = %{A6:alacritty -e htop:}<ramp-load> <label>%{A}

ramp-load-0 = 
ramp-load-0-foreground = ${color.level4}
ramp-load-1 = 
ramp-load-1-foreground = ${color.level3}
ramp-load-2 = 
ramp-load-2-foreground = ${color.level2}
ramp-load-3 = 
ramp-load-3-foreground = ${color.level1}
ramp-load-4 = 
ramp-load-4-foreground = ${color.level0}

label = %percentage%%

click-left = %{A1:alacritty -e htop:} 

[module/memory]
type = internal/memory
interval = 5

format = %{A6:alacritty -e htop:}<ramp-used> <label>%{A}

ramp-used-0 = 
ramp-used-0-foreground = ${color.level4}
ramp-used-1 = 
ramp-used-1-foreground = ${color.level3}
ramp-used-2 = 
ramp-used-2-foreground = ${color.level2}
ramp-used-3 = 
ramp-used-3-foreground = ${color.level1}
ramp-used-4 = 
ramp-used-4-foreground = ${color.level0}

label = %percentage_used%%

[module/filesystem]
type = internal/fs
interval = 3600

mount-0 = /
format-mounted = <ramp-capacity> <label-mounted>

ramp-capacity-0 = 
ramp-capacity-0-foreground = ${color.level0}
ramp-capacity-1 = 
ramp-capacity-1-foreground = ${color.level2}
ramp-capacity-2 = 
ramp-capacity-2-foreground = ${color.level4}

label-mounted = %percentage_used%% (%free%)
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${color.level0}

[module/battery]
type = internal/battery
battery = BAT0
adapter = AC
full-at = 98
time-format = %H:%M
interval = 5

label-discharging = %percentage%% (%time%)

format-charging = <animation-charging> <label-charging>

format-discharging = <ramp-capacity> <label-discharging>

format-full-prefix =  
format-full-prefix-foreground = ${color.level4}

ramp-capacity-0 = 
ramp-capacity-0-foreground = ${color.level0}
ramp-capacity-1 = 
ramp-capacity-1-foreground = ${color.level1}
ramp-capacity-2 = 
ramp-capacity-2-foreground = ${color.level2}
ramp-capacity-3 = 
ramp-capacity-3-foreground = ${color.level3}
ramp-capacity-4 = 
ramp-capacity-4-foreground = ${color.level4}

; plug battery icons
animation-charging-0 =  
animation-charging-1 =  
animation-charging-2 =  
animation-charging-3 =  
animation-charging-4 =  
animation-charging-foreground = ${color.level4}
animation-charging-framerate = 500

[module/xbacklight]
type = internal/xbacklight

format = <ramp> <label>
label = %percentage%%

ramp-0 = 
ramp-0-foreground = ${color.level4}
ramp-1 = 
ramp-1-foreground = ${color.level3}
ramp-2 = 
ramp-2-foreground = ${color.level2}
ramp-3 = 
ramp-3-foreground = ${color.level1}
ramp-4 = 
ramp-4-foreground = ${color.level0}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight
enable-scroll = true


[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-mode-padding = 2
label-mode-foreground = ${color.i3mode-foreground}
label-mode-background = ${color.i3mode-background}


; focused = Active workspace on focused monitor
label-focused = %name% %icon%
label-focused-background = ${color.i3focused-background}
label-focused-foreground = ${color.i3focused-foreground}
label-focused-underline= ${color.i3focused-underline}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %name% %icon%
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
label-visible = %name% %icon%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %name% %icon%
label-urgent-background = ${color.i3alert-background}
label-urgent-foreground = ${color.i3alert-foreground}
label-urgent-padding = 2

; Separator in between workspaces
; label-separator = |
